travis:
  secure:
    BINSTAR_TOKEN: WqjaQneTcZkvRDjIiKBcebjAyOziZZ25HRvFGErHfy9tOlaFaCtnl8UWv+WQ12uTCX/dT1iP8VcCG1LvvOpuv/MYavONxT55yTIhi9R7+t4k/1yLnwuMHMhs4Mnq+ze6IVGMHDFajfhS3PqDZQSX+Mcwkw7EMpSwwptlHYHJ4ecsQB9DLRYVgeLyLVX0yH859QgBpOsAfnR7F40vCC6rC2WcaKd+BRrXSiJfDVjVj7VlYMRlHO13qkiQntiF5j9phv3ArDyJKPbW75wSiDwiniZD9E/wGAIwVgli18UmkY+5/A2ikLamX1h0swcR/9/4+eqrlo5AD28hmd8VstAmFKMP72RCRuItJCgvpOB0mMyPWHeehOPbt2B7JlnliHEKFkvRjt2vY6wSliHzV4yE9k6RfAiBs8dh31i8pQrNg3XD9P8CO4W3vZcJ0o+SXhSyxuqMPF99KsIMtZcA9Cg3qy+aoR5NkMBr7uISg5BGjsXiG+hHNgwPiWYzL0oY7AC+fe6kbQcN8GNVafkb0e7C6u7IG16kRoPnXqdQ+u3lVUik18V8eJnPNeZBihMtrizgMAqVOi7d5qltTQ0shUzfKPZEZF0TD7KWGvdTMvcxXKXYe3ph0OhCWzaND4JgDo79FIjObUh9pd9tJBKoySKXZ2M4+fVL1Xpffju/TQTrFng=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
